name: eastern_dragon
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  flutter:
    sdk: flutter
  go_router: ^11.1.2
  logger: ^2.0.2+1
  mask_text_input_formatter: ^2.7.0
  mobile_device_identifier: ^0.0.2
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  pinput: ^3.0.1
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
