name: eastern_dragon
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bottom_sheet: ^4.0.0
  cached_network_image: ^3.3.1
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_slider_drawer: ^2.1.3
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  go_router: ^11.1.2
  intl: ^0.18.1
  intl_utils: ^2.8.7
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mask_text_input_formatter: ^2.7.0
  mobile_device_identifier: ^0.0.2
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  pinput: ^3.0.1
  responsive_framework: ^1.1.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
    - family: AlumniSans
      fonts:
        - asset: fonts/AlumniSans-Medium.ttf
          weight: 500

# Flutter Intl IDE extension
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: ru # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
